### ISSUE TITLE
Typechecker: Cannot yield after guard in match case

### ISSUE THREAD

**Issue by maddanio** [SerenityOS/jakt#1047]
Should be allowed since guard cannot be a statement. Is also very inconvenient because it basically disallows using guard in match cases.

**Comment by 0GreenClover0** [comment]
Fixed by https://github.com/SerenityOS/jakt/commit/4eeeecd7a990c7c3a9f73601a8f8f753c38d0c0e

**Comment by maddanio** [comment]
thx
