### ISSUE TITLE
Runtime: Requirements for compilation

### ISSUE THREAD

**Issue by trucidare** [SerenityOS/jakt#1059]
Hey,

Which requirements are met for compiling the runtime directory contents?
I want to use jakt for embedded stuff (esp32s3) and the current toolchain 
Supports only c++17 and c++2a

Compiling the generated cpp file with the toolchain throws a bunch of errors
Like declspec(auto) and much more.

Regards
Nils

**Comment by wilsonk** [comment]
I think it requires ```--std=c++20``` but I am new to this, so take with a grain of salt ;) Hopefully someone more experienced will chime in with a definitive answer.

**Comment by trucidare** [comment]
Yeah could get it down to 2 errors. char8_t is not available and explicit(expression) is missing.
explicit is needed for "Optional" :/

Any hint to fix this? Since espressif update strategie is "never touch a running system" - full c++20 will be never available.

**Comment by ADKaster** [comment]
Clang 13 or gcc 11 are required to build the Jakt runtime library, which is the same requirements for building the Serenity OS project (as AK and Jakt are siblings). If the esp microcontrollers have a custom toolchain not based on gcc or clang, then I don't have any advice there.
