### ISSUE TITLE
Cast from negative i16 to u16 crashes at run time

### ISSUE THREAD

**Issue by haakonnessjoen** [SerenityOS/jakt#1124]
```
    let value = -1i16;
    let intermediate = value as! u16;
```

This code will compile, but crash when running the executable. Found when trying to run.
It only crashes if the value is negative.

**Comment by alimpfard** [comment]
That's intentional, the cast you've used is infallible, so if the cast is impossible to do, it will crash.

**Comment by haakonnessjoen** [comment]
Aha, it was a crash i found in the jaktnesmonster project of @jntrnr.
I regretfully don't understand enough jakt to figure out the better way of doing this. I will close the issue.
