### ISSUE TITLE
Windows BUILD

### ISSUE THREAD

**Issue by wilsonk** [SerenityOS/jakt#1132]
I was able to smash things into place to get Jakt to build on Windows 10 with MSYS2 and the bash script below. I am on a slightly older version of MSYS2, but I assume a newer version would also work with it's newer version g++ installed. Here are my specs:

```
MINGW64_NT-10.0-19043 Test_Machine1 3.1.7-340.x86_64 2020-09-22 19:03 UTC x86_64 Msys
```

```
g++.exe (Rev5, Built by MSYS2 project) 10.2.0
```

And here is the bash script (probably a bit fragile, but should suffice if run directly in a newly cloned repo with an MSYS2 shell):

```
#!/bin/bash

# Make a new build directory in case it doesn't already exist
mkdir build

# Build an optimized stage0/jakt.cpp file with c++20 and for a 32-bit target OR
#
# one can choose to build for 64-bit by supplying '-m64' on the command line!!
# I prefer to build for 64-bit, so I left this option in here  :)
#
g++ $1 -std=c++20 -fno-exceptions -Wno-deprecated-declarations -Wno-trigraphs -O3 -o ./build/stage0 -I ./bootstrap/stage0/runtime/ ./bootstrap/stage0/jakt.cpp

# Output the source code for the self hosted jakt compiler, using the mingw64 g++ compiler
# (I think we must do this, as I can't see how to build the final binary directly with stage0's
# command line flags by getting them to pass through the mingw64 g++ compiler directly!!)
./build/stage0.exe -S -C g++ -o jakt ./selfhost/main.jakt

# Build the final self hosted jakt with g++ using the -Os flag for 'optimize for size' and the -mbig-obj flag
# This is necessary as we will get a 'string table overflow' error without the -Os flag
# We will get a 'File too big/too many sections' error without the -mbig-obj flag
g++ -Os $1 -Wa,-mbig-obj -std=c++20 -o ./build/jakt ./build/jakt.cpp  -I ./runtime/
```

**Comment by ADKaster** [comment]
Did using the CMake build steps with your compiler not work? https://github.com/SerenityOS/jakt/blob/main/documentation/cmake-bootstrap.md

**Comment by wilsonk** [comment]
Only needed for MSYS2 build. As long as you have windows binaries of llvm/ninja/cmake in your path then using the instructions from the cmake-bootstrap.md page should work fine.

**Comment by ADKaster** [comment]
I included the -mbig-obj flag and some instructions for extra steps that are MSYS2 specific in https://github.com/SerenityOS/jakt/pull/1125
