### ISSUE TITLE
codegen: 'auto' in template argument when yielding Optional from a match

### ISSUE THREAD

**Issue by cybergsus** [SerenityOS/jakt#1134]
Givin the following code:

```jakt
function my_func() -> i32? => match true {
    false => None
    else => Some(32i32)
}

function main() {
    let a = my_func()
    print("{}", a)
}
```

Clang++ will protest with the following error (among maybe others):

```
build/test.cpp:15:116: error: 'auto' not allowed in template argument
return (JAKT_RESOLVE_EXPLICIT_VALUE_OR_CONTROL_FLOW_RETURN_ONLY(([&]() -> JaktInternal::ExplicitValueOrControlFlow<auto,JaktInternal::Optional<i32>>{
```

Codegen did not have enough information to know what the match expression
yielded but it *did* know however what type will a "return" have:
`JaktInternal::Optional<i32>`. This tends to happen also in try statements or
anywhere where the function returns `Optional<T>` and you yield or return
`None`.

**Comment by robryanx** [comment]
That code seems to work for me.
You can also drop the `Some` around `32i32` as it is using the return type hint.

There are some issues though in inferring the return type though if it is dropped.

```
function my_func() => match true {
    false => None
    else => Some(32i32)
}
```
Maybe it should be able to infer `i32?` from that.

**Comment by cybergsus** [comment]
seems like it's fixed:

```jakt

function my_func() -> i32? => match true {
    false => {
        print("what?")
        yield None
    }
    else => Some(32i32)
}

function main() {
    let a = my_func()
    print("{}", a)
}
```

```
jakt on  1135 !?
❯ build/jakt test.jakt

jakt on  1135 !?
❯ build/test
32%
```
