### ISSUE TITLE
VSCode extension not packagable

### ISSUE THREAD

**Issue by miko007** [SerenityOS/jakt#1188]
When running `npx vsce package` as mentioned in the `README.md` on my M1 mac, i get the following output and no package is created:

```
 ERROR  Command failed: npm list --production --parseable --depth=99999 --loglevel=error --link=true
npm ERR! extraneous: @types/tmp@0.2.3 /<PATH-TO-JAKT>/jakt/editors/vscode/node_modules/jakt-lsp-server/node_modules/@types/tmp
npm ERR! extraneous: @types/vscode@1.64.0 /<PATH-TO-JAKT>/jakt/editors/vscode/node_modules/lsp-sample-client/node_modules/@types/vscode
npm ERR! extraneous: @vscode/test-electron@2.1.2 /<PATH-TO-JAKT>/jakt/editors/vscode/node_modules/lsp-sample-client/node_modules/@vscode/test-electron
```

**Comment by jntrnr** [comment]
If I run the same on my M1 mac, I get a successful build. Not sure what the difference might be.

I'm using vsce 2.11, npm: 8.18, node: 18.8

**Comment by miko007** [comment]
oh i see, it seems my node version was not gonna fly. now with `18.9.0` everything worked as expected. can be closed, i guess.
