### ISSUE TITLE
default arguments dont work for anon args

### ISSUE THREAD

**Issue by maddanio** [SerenityOS/jakt#1203]
```
function say(anon text: String = "WHF") {
    println("{}", text)
}
function main() {
    say()
}
```
doesnt work, but works without the `anon`

**Comment by alimpfard** [comment]
They're not supposed to, arguments with defaults must not be anon (perhaps we should make that an explicit error)

**Comment by maddanio** [comment]
whats the reasoning for that? the only functional reason I can see is ambiguity when there are multiple anon args, but then one could simply mandate that defaults are applied back to front, pretty much how it works in c++.
where this annoyed me was that in the parser there is the `peek`function taking as argument the number of steps and it seems very natural to me to have a default of 1 there (i.e. peek "just ahead") but thats not possible...

**Comment by maddanio** [comment]
and yes, if there should be concensus to not allow defaults on anon args (though I cannot see why) then it should not be allowed to specify them

**Comment by awesomekling** [comment]
This issue no longer reproduces :)
