### ISSUE TITLE
Imports/includes

### ISSUE THREAD

**Issue by linusg** [SerenityOS/jakt#121]
Being able to split code across files is crucial for writing maintainable and reusable software. No strong feelings regarding syntax and actual implementation.

**Comment by awesomekling** [comment]
Let's prioritize finding an approach that optimizes for build time.

**Comment by bbkane** [comment]
Also consider IDEs as clients - see https://rust-analyzer.github.io/blog/2020/07/20/three-architectures-for-responsive-ide.html

**Comment by bbkane** [comment]
@lanmonster , could you drop a docs link about how included/imports work now or link to a commit?
