### ISSUE TITLE
Sets

### ISSUE THREAD

**Issue by linusg** [SerenityOS/jakt#122]
I want syntax for sets pls, they're underrated. But not in a way Python does it where an empty set can't be represented with set syntax, because it's actually an empty dict...

**Comment by bradms** [comment]
What do you think about the way Clojure defines sets? I.e., `#{1 2 3}` instead of `{1 2 3 4}` which is a map.

**Comment by mustafaquraish** [comment]
yikes, sorry for the spam here, I don't know why I thought tagging the issue in a commit was a good idea

**Comment by linusg** [comment]
No worries, it's usually a good idea to reference issues! If you put `Closes #1234` next time it'll automatically... well, close the issue once merged.
