### ISSUE TITLE
miscompile with functions in struct

### ISSUE THREAD

**Issue by wtholliday** [SerenityOS/jakt#1226]
main.jakt:

```
import foo
```

foo.jakt:

```
struct Foo {

   function a() { }
   function b() { a() }

}
```

running `./build/bin/jakt main.jakt` I get:

```
build/foo.cpp:15:1: error: no member named 'a' in namespace 'Jakt::foo'; did you mean simply 'a'?
foo::a();
^~~~~~
a
build/foo.cpp:8:16: note: 'a' declared here
void foo::Foo::a() {
               ^
1 error generated.
Error: Compilation failed
```

Note that this works when `Foo` is simply in main.jakt.

**Comment by wtholliday** [comment]
Seems like in `codegen_call` we need to detect when calling a static method via `function_.is_static()` and then append the struct name as a namespace. So `issue_1226_sub::Foo::a` instead of `issue_1226_sub::a`.

**Comment by wtholliday** [comment]
Wondering why `struct_id` is `None` here: https://github.com/SerenityOS/jakt/blob/c0e8f6cb9dedcab13b39a82fde028941160fe4a1/selfhost/typechecker.jakt#L1432

**Comment by awesomekling** [comment]
This issue no longer reproduces :)
