### ISSUE TITLE
jakttest: Spins at ~100% CPU on Linux while tests are running

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/jakt#1228]
A quick `strace` shows us that we're aggressively doing `wait` syscalls:

```
wait4(-1, 0x7ffcf9e0658c, WNOHANG, NULL) = 0
wait4(-1, 0x7ffcf9e0658c, WNOHANG, NULL) = 0
wait4(-1, 0x7ffcf9e0658c, WNOHANG, NULL) = 0
wait4(-1, 0x7ffcf9e0658c, WNOHANG, NULL) = 0
wait4(-1, 0x7ffcf9e0658c, WNOHANG, NULL) = 0
wait4(-1, 0x7ffcf9e0658c, WNOHANG, NULL) = 0
wait4(-1, 0x7ffcf9e0658c, WNOHANG, NULL) = 0
wait4(-1, 0x7ffcf9e0658c, WNOHANG, NULL) = 0
...
```

This should definitely not be necessary, so something here needs a rework.

**Comment by demizer** [comment]
These wait calls are from python `subprocess.communicate()` which is used by `run_one.py` to make the test pipeline of "jakt -> clang -> check test output" portable and easier to maintain (I imagine).

The very last test of a no-arg jakttest run is build testing the selfhost compiler. The long delay at the end (and the barrage of wait calls) is python waiting for the jakt compiler to compile selfhost.

Adding `/// Expect: Skip` in `selfhost/main.jakt` fixes the problem of the long wait (and ridiculous amount of syscalls), but doesn't eliminate it entirely.

**Comment by cybergsus** [comment]
Taking a look at this now. Looks like the barrage of wait syscalls comes from Jakttest, not from python. This is a frame from `strace -k build/bin/jakttest selfhost.jakt`:
![image](https://user-images.githubusercontent.com/54634335/222970182-c3019379-56ea-4ad4-a8ac-db40fc28551b.png)
