### ISSUE TITLE
Path::basename has an edge-case problem with Windows file paths

### ISSUE THREAD

**Issue by Holladiewal** [SerenityOS/jakt#1235]
The Path::basename function does not handle Windows paths correctly.
Given the following to Jakt files:
test.jakt: 
```jakt 
import test2 {}
function main(){} 
```

and test2.jakt being empty (this would also work with code in test2.jakt)
causes an abort as the subtraction underflows while trying to substring the basename of the path.

However, this only happens when the path given in the invocation to jakt starts with a . (like ```jakt .\src\test.jakt``` or ```jakt ./src/test.jakt```).
It seems to try determining where the suffix starts, but continues it's search until the initial dot, which obviously precedes the starting point of the file name.

If the given filename does not include the starting dot (like ```jakt src\test.jakt```) it will compile without problems.

**Comment by alimpfard** [comment]
I can't seem to repro this, 
The mwe you gave works fine on linux:
![image](https://user-images.githubusercontent.com/14001776/198958006-75531310-a3bf-4253-bd40-24133180e669.png)

and Path behaves correctly with windows separators:
```
> import os { Target }
> Target::active()
= Target(arch: "x86_64", platform: "pc", os: "windows", abi: "msvc")
> import path { Path }
> let path = Path::from_string(".\\src\\test.jakt")
> path
= Path(path: ".\\src\\test.jakt")
> path.basename()
= "test.jakt"
> path.basename(strip_extension: true)
= "test"
```

**Comment by Holladiewal** [comment]
My provided MWE does indeed work now. Going through the commit history and trying to reproduce it, the first commit where this issue does not occur anymore is 2d88f26ae4afab6a93f8bc8acb09e6fd4dda136e.

However that commit does not seem to touch anything directly related to the error. 
This example does still trigger the crash.
```jakt
import path { Path }
function main(){
    let path = Path::from_string(".\\src\\test2")
    println("{}", path)
    path.basename(strip_extension: true)
}
``` 

Following the code further, it seems that in Path::extension() there is a fixed check for '/' as a path seperator which, if replaced by a call to `get_path_seperator()`, makes the above example work.
