### ISSUE TITLE
Is Clang on MSYS2 supported?

### ISSUE THREAD

**Issue by 3oheicrw** [SerenityOS/jakt#1237]
Since the Supported Platforms only note about MSYS2 g++?

https://github.com/SerenityOS/jakt/blob/main/documentation/cmake-bootstrap.md

**Comment by ADKaster** [comment]
It might work, have you tried it and run into an issue?

**Comment by 3oheicrw** [comment]
> It might work, have you tried it and run into an issue?

No. I asked before trying. As he said he will not fix bugs reported for MSYS2 g++ so I'm asking if the same applied to MSYS2 clang. I will not try if bugs reported for MSYS2 clang not accepted like with MSYS2 g++.
