### ISSUE TITLE
Generic inference issues when there are multiple `TypeId`s for `TypeVariable("T")`

### ISSUE THREAD

**Issue by robryanx** [SerenityOS/jakt#1283]
```
struct Foo<T> {
    value: [T]

    function get(this) -> T {
        let temp: T = .value[0]

        return temp
    }
}

function main() {
    mut foo = Foo(value: [1])

    println("{}", foo.get())
}
FIXME: Make this compile in a nice way
```

As best as I understand ends up being that value type T and temp type T end up being 2 different types, 1 being in the prelude module, generic inferences has a replacement for 1 but not the other when typechecking let val: T = .value[0] so it gives an error expected ‘i64’, but got ‘T’

I wonder if we need some system where because we have struct Foo<T> we know within the context of the struct every T is the same. Maybe this is already handled with traits because for example Iterable<T> would also have a separate type id in a separate module.

**Comment by cybergsus** [comment]
Looks like this has been solved as of 1e622329894ef5a148d52b75afabe67063cd4bef.
