### ISSUE TITLE
Usage of String::push_str instead of write macro

### ISSUE THREAD

**Issue by wert007** [SerenityOS/jakt#129]
I have seen in [codegen.rs](https://github.com/awesomekling/jakt/blob/d55b4664cfafdb79dc5b50ac7882a09347a681d5/src/codegen.rs#L98), that you use `String::push_str`:

```rust
            output.push_str("enum class ");
            output.push_str(&enum_.name);
            output.push_str(": ");
            output.push_str(&codegen_type(ty, project));
            output.push_str(" {\n");
```

This could be replaced with the `write!` or `writeln!` macro, if `std::io::Write` is in scope.

```rust
            writeln!("enum class {}: {} {{", enum_.name, codegen_type(ty, project));
```

This would also be a good first step into moving away from heap allocated strings as output and using the `Write` trait as output.

But while `String::push_str` returns a `()` type, the `write!` macros return `Result<(), std::io::Error`, which would need to be handled in some capacity.

I would be interested to hear, how you feel about this.

**Comment by guerinoni** [comment]
`push_str` generates less code and usually can't fail

**Comment by wert007** [comment]
Hmm, I have to admit, I wasn't aware of `String::push_str` generating less code. Maybe one could argue in favor of readability, but I was not aware of the drawbacks. 😅

**Comment by guerinoni** [comment]
Can this be acceptable?
```rust
    if enum_.underlying_type.is_some() {
        let ty = enum_.underlying_type.unwrap();
        if is_integer(ty) {
            let mut output = format!(
                r#"enum class {}: {} {}"#,
                enum_.name,
                codegen_type(ty, project),
                "{"
            );
            for variant in &enum_.variants {
                match variant {
                    CheckedEnumVariant::Untyped(name, _) => {
                        output.push_str(format!("    {name},").as_str())
                    }
                    CheckedEnumVariant::WithValue(name, value, _) => {
                        output.push_str(
                            format!("    {name} = {},", &codegen_expr(0, value, project)).as_str(),
                        );
                    }
                    _ => unreachable!(),
                }
            }
            output.push_str("};\n");
            return output;
        } else {
            todo!("Enums with a non-integer underlying type")
        }
    }
```

**Comment by wert007** [comment]
I mean acceptable is anything, I am not the one accepting. I just took the enum as a example and meant more the whole file. 😅 

But yeah, I think this is better readable. I still think using `write!` would be shorter to write, but I understand, that that is not really important.

**Comment by alimpfard** [comment]
When the toolchain updates to use Clippy v0.1.63, clippy will get mad at the `push_str(format!(...))` pattern, anything else is better left as `push_str()`.

**Comment by guerinoni** [comment]
Ok thanks! We can close this :D
