### ISSUE TITLE
jakt in github/linguist?

### ISSUE THREAD

**Issue by ghost** [SerenityOS/jakt#1291]
Hi all.

I wonder if you've all thought about adding jakt to [github/linguist](https://github.com/github/linguist). *You've all thought about adding jakt to [github/linguist](https://github.com/github/linguist)?*

**Comment by alimpfard** [comment]
We currently do not meet their minimum requirements for inclusion (atm at least 2k files): https://github.com/search?q=path%3A%2F.*%5C.jakt%24%2F&type=code
