### ISSUE TITLE
Using chained methods in a generic class gives compiler warning and crash

### ISSUE THREAD

**Issue by hughdavenport** [SerenityOS/jakt#1300]
Hey folks,

I'm having the following fail to compile:

```
/// Expect:
/// - output: "false\n"

function main() {
    mut f: Foo<String> = Foo()
    f.bar()

}

class Foo<T> {
    data: T? = None

    public function baz(this) {
        println("{}", .data.has_value())

    }

    public function bar(this) {
        .baz()
    }

}
```

The error I get is:
```
15:56 $ ./build/bin/jakt samples/generics/generic_class_method_chaining_rebinding.jakt
Warning: Generic parameter 1_19 is being bound to itself
Aborted (core dumped)
```

The following changes will make this work as expected:
- Remove the generics
- Change the println to `println("Hello World")`
- Remove `bar` and call `f.baz()` instead

The following changes have no effect, and still cause compiler crash:
- Using `this.data` instead of `.data`
- Using other statements that use `this.data` or `.data`, e.g. `.data = None`

I'm keen to help debug this and make a PR for it. I've got a couple more issues I've found with generics to file as well.

Cheers,

Hugh

**Comment by hughdavenport** [comment]
A possible fix I have for this is the following:

```
diff --git a/selfhost/typechecker.jakt b/selfhost/typechecker.jakt
index c1429c8..e5a76b1 100644
--- a/selfhost/typechecker.jakt
+++ b/selfhost/typechecker.jakt
@@ -5170,7 +5170,11 @@ struct Typechecker {
                 let checkpoint = .generic_inferences.perform_checkpoint(reset: false)
                 defer .generic_inferences.restore(checkpoint)

-                .map_generic_arguments(type_id, args)
+                if checked_expr is Var(var) and var.name == "this" { } else {
+                    // It doesn't make sense to map all the generics on `this`
+                    // as it would have already been done earlier
+                    .map_generic_arguments(type_id, args)
+                }

                 match type {
                     GenericInstance(id: struct_id) | Struct(struct_id) => {

```

It seems a bit hacky to me, but gets it working for what I'm wanting to do. Basically if we find that we are "this" on a generic instance, then don't map the generic arguments (as we would have done it in the past).

It'll probably be an issue with a generic enum instance as well, as the call to `.map_generic_arguments` happens in that match branch as well.

If you think this patch doesn't look too hacky then let me know and I'll make a PR for it.

Cheers,

Hugh

**Comment by hughdavenport** [comment]
A maybe better patch could be:
```
diff --git a/selfhost/types.jakt b/selfhost/types.jakt
index 771ca0c..58de630 100644
--- a/selfhost/types.jakt
+++ b/selfhost/types.jakt
@@ -12,8 +12,7 @@ struct GenericInferences {

     function set(mut this, anon key: String, anon value: String) throws {
         if key == value {
-            println("Warning: Generic parameter {} is being bound to itself", key)
-            abort()
+            return
         }

         let mapped_value = .map_name(value)
```

**Comment by awesomekling** [comment]
This issue no longer reproduces :)
