### ISSUE TITLE
Current sample apps don't compile

### ISSUE THREAD

**Issue by HectorPeeters** [SerenityOS/jakt#131]
On the latest main branch, both the cat and crc32 sample programs fail with the following error: `Condition must be a boolean expression`.

To prevent this in the future, it might be a good idea to add these to `cargo test`.

## Cat

For the cat example, compilation fails because of the following line:
```jakt
20:    while not feof(file) {
```

Since feof returns a c_int and while expects a boolean. Changing the condition to `feof(file) == 0` does not work as comparisons between `c_int` and normal numeric types is not supported.

## CRC

For the crc example, the incorrect line is the following:
```jakt
14:    if value & 1 {
```

Here, `value & 1` does not result in a boolean value. Replacing this with `value & 1 != 0` would solve the problem but that again needs the `c_int` and numeric comparisons.

**Comment by linusg** [comment]
I (unknowingly) broke that in https://github.com/SerenityOS/jakt/commit/362cc4deaa39c94640d460360f209d483a26f649 - we could of course also allow numeric expressions as boolean conditions, but I think keeping it explicit is the way to go (and matches the clang-tidy warning for implicit boolean conversions recently enabled in serenity).

**Comment by HectorPeeters** [comment]
Yes I think that explicit would indeed be the way to go here as it matches more with the safety aspect of jakt. 

I would like to work on the fix for this issue myself by allowing comparisons with `c_int` types but as the size of the `c_int` type is compiler dependent should it be handled as such or can I assume its a normal 32 bit integer?
