### ISSUE TITLE
I just built jakt but I get this error

### ISSUE THREAD

**Issue by OLD-DATA** [SerenityOS/jakt#1495]
Error: No module in module set {jakt::prelude::prelude} was found

**Comment by alimpfard** [comment]
You'll probably get a faster response for build issues in `#jakt` on discord, that error means jakt couldn't find its runtime dir where it expected to find it (`../include/runtime` relative to the binary).
If you're on windows, I think the symlink thing we ask cmake to do still fails, so maybe try passing `--runtime-path $jakt_checkout_root/runtime` to the compiler.

**Comment by OLD-DATA** [comment]
ok thank you & have a good day
