### ISSUE TITLE
Point out missing `throws` for functions that can fail

### ISSUE THREAD

**Issue by mustafaquraish** [SerenityOS/jakt#153]
Currently, if a `foo()` not marked with `throws` calls another function `bar()` which does throw an error, the compiler doesn't point this out, and instead generates incorrect cpp code. This should ideally be caught before we generate any code. 

Example:
```
function bar() throws -> i64 { return 5 }
function foo() -> i64 { return bar() }
```

**Comment by ADKaster** [comment]
More specifically it should be an error to call a function that throws *outside of a try block* in a function that doesn't throw 🙂

**Comment by AndrewBregger** [comment]
I'm wanting to contribute to this project. Can I take this issue if noone else is working on it. Thanks.
