### ISSUE TITLE
Negate operator allows assigning a reference to an object

### ISSUE THREAD

**Issue by 0GreenClover0** [SerenityOS/jakt#1581]
```rs
fn main() {
    let i = 1
    let ref = &i

    let x: i64 = *ref // Good, compiles
    let y: i64 = ref // Bad, error
    let z: i64 = -ref // Bad, compiles
}
```

**Comment by alimpfard** [comment]
This is fine? the reference is just automatically dereferenced prior to the negation.
the reason I made plain assignments not auto-deref was mostly because I thought it'd have been ambiguous.

**Comment by 0GreenClover0** [comment]
Hmm, okay. I don't really like the inconsistent behavior, it made me confused :c

**Comment by alimpfard** [comment]
Would you rather we didn't auto-deref, or atuo-deref when assigning &T to T?

**Comment by 0GreenClover0** [comment]
Currently probably auto-deref. But I would need to play with references a bit more to see and decide
