### ISSUE TITLE
Make many clippy warnings a hard error

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [SerenityOS/jakt#169]
In doing #168, I found a couple of ridiculous patterns, like the `match` for a single variant. We should probably do `#[deny(clippy::all)]` or at least some of the lints we find offensive so that we can automatically prevent them from getting through code review.

CC @jntrnr, is this something that sounds good? I'm very unsure as I love doing `#[deny(clippy::all, clippy::pedantic, clippy::nursery)]` in personal projects, which is too much here, but having the linter create hard errors is a good thing IMHO.

**Comment by jntrnr** [comment]
yeah I'm okay with ignoring a few of the more picky lints that don't seem to add much (like the single variant match)

**Comment by kleinesfilmroellchen** [comment]
No, I'd actually suggest making single variant match a hard error, because it creates unnecessary mental overhead and extra indentation. But we can discuss the details; I'll throw a PR later today after I have the basic integer overflow checks ready
