### ISSUE TITLE
Weak references

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/jakt#170]
`weak T?` should behave essentially like `Optional<T&>` in C++ but with the added feature that it automatically empties itself when the `T` is destroyed.

`weak T` is not allowed, since that implies it's always in a dereferenceable state.

**Comment by sin-ack** [comment]
Hmm, shouldn't `weak T` imply `T?`? Because there is no other possible state for a weak pointer, I don't really see the point of requiring additional tokens when `weak` provides adequate meaning regardless.

**Comment by awesomekling** [comment]
The `?` token is for readability, and symmetry with other optional types.
