### ISSUE TITLE
Remove inline C++

### ISSUE THREAD

**Issue by jmalcolm137** [SerenityOS/jakt#207]
I may be more excited about Jakt in some ways than I am about Serenity. It makes a lot of nice choices including some very sane choices in terms of making it unambiguous to parse. It is easy to imagine how the syntax could be extended in the future. Of course, it solves the hardest new language problem as well which is “nobody is going to use it” as the footprint of Serenity alone probably guarantees at least some level of exposure and success.

What I cannot wrap my head around is “in-line C++”. This seems like a big design mistake. It is easy to see how this would be implemented now. I can imagine it will also seem handy at first as an escape hatch for missing features. But how will this work when Jakt is doing its own code generation? It would require an embedded C++ parser. That project alone is bigger than the rest of Jakt ( I think I would rather implement my own OS than implement C++ ). How does reference counting work when there is inline C++? One of the benefits of Jakt seems to be that it will be so much easier to understand than C++. But with inline C++, I might have to know C++ to understand a Jakt program. Another advantage, especially as the Serenity mono-repo grows, is faster compile times. But embedded C++ kills that too. Inline C++ seems like a nightmare.

Would it be possible to consider embedded C++ as a feature of the compiler ( of this specific implementation ) instead of as a feature of the language? Kind of like GCC extensions?

I guess I am hoping for this feature to be removed. If not removed, at least treated uniquely in the hopes that it could be removed long term. Or discouraged so that it is used only sparingly in practice.

Thinking ahead, what makes C++ so special anyway? I mean, it is what SerenityOS is written in but the stated goal is to rewrite in Jakt. Jakt itself is written in Rust after all ( though it will hopefully be written in Jakt as well at some point ).

**Comment by kleinesfilmroellchen** [comment]
So yes, Jakt will one day be written in Jakt. However, the first implementation will still be a C++ transpiler because that's easier. I do consider inline C++ a glue feature right now, once we have good FFI we can always extract the C++ code into other files. That's also what should happen for Serenity-internal Jakt.

**Comment by awesomekling** [comment]
Inline `cpp` blocks are a glue feature to help us bring up the language and incrementally port the system over.

If we stop transpiling to C++, we'll stop supporting inline C++. :^)

**Comment by jmalcolm137** [comment]
I know this is closed…

If you already plan to remove something later, i think it makes a lot of sense to treat this a feature of the compiler but not as part of the language. That sets the right expectation with everybody.

Regardless, I am happy to see that the thinking is at least that this will not be a feature of the language long term.
