### ISSUE TITLE
Implement var keyword

### ISSUE THREAD

**Issue by jmalcolm137** [SerenityOS/jakt#209]
One area where I personally see Jakt as hard to read is `let mutable`. After `let`, my brain wants to see an identifier. Can you declare more than one identifier per line? Is it `let mutable a, mutable b` or `let mutable a, b`? If the latter, it is really ambiguous. If the former, that is some real estate inflation if I want to declare say 5 mutable identifies in something like a math function.

We can say that Jakt is “immutable by default” but in the first two app samples there is mutability everywhere.

Consider reserving `let` to mean immutability unambiguously. Then use `var` when mutability is wanted.

Instead of
```
let mutable c = fgetc(file)
while feof(file) == 0 {
     putchar(c)
     c = fgetc(file)
} 
```

we would write
```
var c = fgetc(file)
while feof(file) == 0 {
     putchar(c)
     c = fgetc(file)
} 
```

**Comment by kleinesfilmroellchen** [comment]
My 2c: It should by intentionally more difficult to write mutable variables, as immutability is good and the default.

**Comment by jmalcolm137** [comment]
The Jakt intro makes the point that code is read more than it is written and that readability should be a priority. I agree with this.

IDE support will take away most of the pain of writing `mutable` every time anyway. You can see this support being added already. I doubt idiomatic Jakt will be deeply forged by the difference between `let mutable` and `var`. One just looks a lot nicer and allows me to understand the code more quickly ( if I see `let` right now I have to pause and ask which kind of `let` it is ).

**Comment by linusg** [comment]
>  if I see let right now I have to pause and ask which kind of let it is

No, it's the other way around. If you see let, you just continue reading to see which kind of let it is. When you see let or var, you have to stop thinking which one is which.

**Comment by jmalcolm137** [comment]
Well, Andreas implemented it as the `mut` keyword instead of `var` but I got my wish as of commit a2b238d14a0f70f6374b02f9c2fc0337cb2c9d14
