### ISSUE TITLE
Parser infinite loop when setting enum value to unclosed bracket

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/jakt#233]
For example:
```
enum a { b=[ }
```

**Comment by Lubrsi** [comment]
Related:
```
enum foo bar{
```

**Comment by cybergsus** [comment]
I've been taking a look at `src/parser.rs` and the first one seems like `parse_array` could skip the token if there was an error, and then for both it would be a matter of expecting the current token to be a closing token (`]` in case of array/dict and `}` in case of enum).

I'll be working on this, if no one has already takeni t.

**Comment by cybergsus** [comment]
although I'd suggest changing to using `Result<T, JaktError>` from parser functions and make some error types part of enums to be easily pattern-matched in case of the error being recoverable, although the default thing to do (using `Try`'s `?`) would be bailing out if an error ocurred when calling another parser.
