### ISSUE TITLE
Question : Do you consider adding operator overloading to Jakt?

### ISSUE THREAD

**Issue by serge-hulne** [SerenityOS/jakt#248]
I am looking for a new language that woulld be a replacement for Fortran for scientific computing.

I have considered : Nim, V, Crystal, Odin, Julia, Go, Swift, but they all have their own quirks and issues.

Therefore, I was wondering if you plan to implement operator overloading in Jakt.

**Comment by kleinesfilmroellchen** [comment]
There have been talks about how to exactly go about it, but I think there's some level of agreement that operator overloading is a desirable feature. The *how*, as said, is still an open question. I myself advocate for "magic interface"-based overloading (e.g. Rust), but that's not a consensus.

**Comment by awesomekling** [comment]
Please direct questions to Discord.
