### ISSUE TITLE
Cannot assign `T` to `T?`

### ISSUE THREAD

**Issue by lanmonster** [SerenityOS/jakt#307]
Expected behavior:
```
function main() {
    let a: String = None
    a = "hello"
}
```
should compile

Actual behavior:
<img width="743" alt="image" src="https://user-images.githubusercontent.com/3748720/170136677-78c31d10-9cc5-4d7d-a71e-f86d0e56141e.png">

**Comment by mustafaquraish** [comment]
Did some digging around, it seems that currently for `BinaryOp::Assign` we just check if `lhs_type_id == rhs_type_id`. We do already have some logic to handle optionals and weak pointers in `check_types_for_compat`, which is called from `unify_with_type_hint` (a lambda created in `typecheck_expression`). I suspect that we can re-use almost all of this logic, we just need to handle the regular assign operation separately.

I'm not working on this for now, but if anyone wants to go ahead and do this and wants to have a chat about it, feel free to ping me on discord

**Comment by AndrewBregger** [comment]
If @lanmonster is not working on this I will.

**Comment by lanmonster** [comment]
@AndrewBregger go for it!

**Comment by mustafaquraish** [comment]
Fixed in 56bbf1
