### ISSUE TITLE
Binary operations don't work on "incompatible" types

### ISSUE THREAD

**Issue by mattisboeckle** [SerenityOS/jakt#324]
```
let a : f32 = 3.2
let b : i32 = 5
println("{}", a+b)
```
Does not compile

**Comment by mustafaquraish** [comment]
What would you expect the output here to be? Should `a+b` give you an `i64` or `i32`? Personally, I like that there's no implicit conversions and that you need to specify which value needs to be converted to which type.

If you're suggesting implicit conversions, what would be the mechanism to go about figuring out which type to convert to? How would this work with other types such as floats, etc?

**Comment by mattisboeckle** [comment]
I'm so used to implicit conversions that I just expected it to work like this, but we probably don't need them. 
What I'm actually after is 
```
let a : f32 = 3.2
let b : i32 = 5
println("{}", a+b)
```
or something similar. I should probably change the example.

And I would expect this to implicitly cast the i32 to an f32.

**Comment by linusg** [comment]
no implicit conversions - `a + b as! f32` is how you'd do that, see https://github.com/SerenityOS/jakt/blob/main/samples/math/integer_casts.jakt
