### ISSUE TITLE
Error with opening curly brace on newline

### ISSUE THREAD

**Issue by gdelazzari** [SerenityOS/jakt#330]
The following code doesn't compile
```
function main()
{
  print("Hello!")
}
```
with the compiler complaining
```
Error: expected complete block
-----
-----
```

I guess the parser expects `{` to be the next token after the function declaration, without ignoring newlines.

Is this intended as a way to enforce code style like Golang does? If not, maybe the error message could be better?

**Comment by supex0fan** [comment]
The error message will be fixed by #259. Whether that should be an error is another story.
