### ISSUE TITLE
Confusing error when defining => functions with a -> type

### ISSUE THREAD

**Issue by AtkinsSJ** [SerenityOS/jakt#331]
Functions defined using `=>` have their return type inferred automatically, and are not allowed to have it stated explicitly with `-> Foo`. However, the error you get is not at all clear. With this example code:

```jakt
class Limited {
    public function get_secret() -> String => "Shhhh! Don't tell anyone!"
}

function main() {
    Limited::get_secret();
}
```

...we get this error:

```
Error: expected field
----
 6 | } 
----
```

A better error would tell you that the method definition is invalid because of the `-> String`, and point to it.

EDIT: Alternatively, maybe explicit return types should be allowed and override the inferred one? Either way, this is a confusing error.

**Comment by awesomekling** [comment]
Allowing explicit return types seems reasonable.

**Comment by cybergsus** [comment]
on my way to implement it!
