### ISSUE TITLE
clang warning on macOS

### ISSUE THREAD

**Issue by mustafaquraish** [SerenityOS/jakt#359]
I get this warning on macOS using `cargo run file.jakt`:

```
warning: unknown warning option '-Wno-unqualified-std-cast-call'; did you mean '-Wno-qualified-void-return-type'? [-Wunknown-warning-option]
```

**Comment by 0verse** [comment]
I get it too. I use musl-libc based custom distro tough.

**Comment by BertalanD** [comment]
This flag was added to Clang in [February 2022](https://github.com/llvm/llvm-project/commit/70b1f6de539867353940d3dcb8b25786d5082d63), about a month after LLVM 14 had already branched off.

I don't think the Jakt driver should concern itself with adjusting the compile flags based on the compiler's version (which would especially not be fun as Apple Clang exists), so I'd rather disable `-Wunknown-warning-option` instead.

**Comment by mnlrsn** [comment]
FWIW, I commented out line 76 in main.rs, and enjoy the silence.
