### ISSUE TITLE
Assigning None to non-optional type

### ISSUE THREAD

**Issue by intrnlerr** [SerenityOS/jakt#371]
```
function main() {
    let x: i32 = None
}
```
This should show an error before codegen

**Comment by onsah** [comment]
Hi, I can take up this issue but need more detail. Is there a convention for error message format?

**Comment by onsah** [comment]
I tested it and it seems to be resolved. When I run the example I get 
```
Type mismatch: expected ‘i32’, but got ‘unknown’
```
The error message may be polished but it errors out in type check phase.
