### ISSUE TITLE
typechecker: "Condition must be a boolean expression" when branching on return value from fat arrow function

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/jakt#380]
This program fails to compile:
```
function moop() => true

struct Class {
    function foop(this) {
        if moop() {
        }
    }
}

function main() {
}
```
Error:
```
Error: Condition must be a boolean expression
----- sup.jakt:5:12
 3  |     function foop(this) { 
 4  |         if moop() { 
                 ^- Condition must be a boolean expression
 5  |         } 
-----
```

**Comment by cybergsus** [comment]
tracked it down to `typecheck_method` running before `typecheck_function`, resulting in `typecheck_method` viewing the `moop` function return as `unknown`.

**Comment by cybergsus** [comment]
perhaps we should order our typechecking based on dependencies (X needs type from Y in outer scope) to make sure that typechecks run in the correct order.

**Comment by cybergsus** [comment]
that or do the type inference from the block in `typecheck_function_predecl` instead of `typecheck_function`.
