### ISSUE TITLE
typechecker: Block return detection ignores returns in `match` expressions

### ISSUE THREAD

**Issue by alimpfard** [SerenityOS/jakt#394]
```
enum Foo {
    Id(i64)
    Name(String)
}
function test(x: Foo) -> String {
    match this {
        Name(name) => {
            return name
        }
        Id(id) => {
            return format("anon:{}", id)
        }
    }
}
```

Errors with "control reaches end of non-void function", but `match` must always be exhaustive, and all its arms return from the function.

**Comment by creator1creeper1** [comment]
It doesn't seem simple to do exhaustive analysis of the control flow of a function. Could at least this case not be written more succinctly as
```jakt
enum Foo {
    Id(i64)
    Name(String)
}
function test(x: Foo) -> String {
    return match this {
        Name(name) => {
            name
        }
        Id(id) => {
            format("anon:{}", id)
        }
    }
}
```
?

**Comment by mustafaquraish** [comment]
@creator1creeper1 it might be nice to have this check anyway, even if the specific example can be written better.

**Comment by alimpfard** [comment]
Note that match exhaustiveness is already checked, so the return checker can (and should) assume that control will not fall out of match, exactly one of the match arms will be executed.

The provided example is silly, but that's just to demonstrate the issue.

**Comment by maddanio** [comment]
oh, thats interesting. I think fixing that could well b included in https://github.com/SerenityOS/jakt/pull/491

**Comment by maddanio** [comment]
the weird thing here is that match would have to behave differently based on wether its result is consumed or not. is that desired?

**Comment by cybergsus** [comment]
> oh, thats interesting. I think fixing that could well b included in #491

no, this pull request just fixes codegen, nothing to do with type inference, which is what you're looking for. I responded in the discord with a longer message explaining what is happening: https://discord.com/channels/830522505605283862/976984180313452604/982246663278198824

**Comment by maddanio** [comment]
> I'd leave the first sample as ill-formed and favor the second sample since it can be directly mapped to a fat arrow:

hmm, ok, then the checker would have to track wether the result of a match is consumed and disallow return statements otherwise. basically a kind of `nodiscard` on match returns.

**Comment by cybergsus** [comment]
I was doing some samples on #491 and typechecker did not catch that I was returning an integer instead of `String` (which I had stated previously when I was iterating on the sample). So even though I don't like the first sample, we should track return types from all branches.

**Comment by F35idk** [comment]
From what I can tell the return analysis as it's implemented doesn't cover match expressions - only ifs, loops, blocks, etc. The [following](https://github.com/F35idk/jakt/commit/b1e0d159b9070229d365e6751d63eca6d438920c) seems to fix the issue in the typechecker, but still leaves compilation errors on the cpp side.

**Comment by cybergsus** [comment]
I'm going to check that out and see what happens if you haven't hit the solution yet. If you want to begin a PR that doesn't pass everything yet it would be great

**Comment by cybergsus** [comment]
hmm, looks like an issue of `try` inside `match`.

**Comment by F35idk** [comment]
Sure, thanks. I've opened a PR with the sample you gave ↑
