### ISSUE TITLE
Swift-style `guard`

### ISSUE THREAD

**Issue by thislooksfun** [SerenityOS/jakt#452]
Swift has an (in my opinion) excellent feature called `guard` (can't link directly to it, but it's on [this page](https://docs.swift.org/swift-book/ReferenceManual/Statements.html)), which is implemented as an `if not` block that ***must*** exit the current scope (compiler error if you forget). It improves readability since you can define what you *do* want the state to be, rather than what you *don't*, and it prevents bugs by not letting you forget to `return` (or `throw`, or `break`, or `continue`). The code @awesomekling wrote in the recent Jakt-native JSON parser would be (imo) a lot cleaner with the use of a `guard`-like syntax.

**Comment by awesomekling** [comment]
Yes, I think the `guard` thing in Swift is neat and we should totally have it.
