### ISSUE TITLE
parser: type confusion in array initializer

### ISSUE THREAD

**Issue by mnlrsn** [SerenityOS/jakt#472]
The following code produces an error in the initialization of the array. The error manifests itself when an array is initialized and being passed to a function call as a parameter at the same time.

Error message:
```
 6  |     let c = f(a: [1.0f64; n])
                                ^- Type mismatch: expected ‘f64’, but got ‘i64’
```

Code producing the error:
```
function f(a: [f64]) {
    return 0
}

function main() {
    let n : i64 = 1
    let c = f(a: [1.0f64; n])
}
```

If I make an explicit cast of `n` to `i64` it works:
```
function main() {
    let n : i64 = 1
    let c = f(a: [1.0f64; n as! i64])
}
```
It also works as expected if the array initialization is done on a separate line:
```
function main() {
    let n : i64 = 1
    let d = [1.0f64; n]
    let c = f(a: d)
}
```

**Comment by ADKaster** [comment]
I'm not sure I understand where the confusion is here? You have a floating point literal and an integer lvalue. Those are different types, so it fails to deduce the array type.

What do you expect to happen here?

**Comment by mnlrsn** [comment]
> 



> What do you expect to happen here?

I expected it to create an array of floats (indicated by the 1.0f64) of size 1 (as specified by the variable n). Notice the semicolon (;) in the array initializer.

It compiles if I make an explicit cast to i64. Will update the example.

**Comment by mnlrsn** [comment]
It also works as expected if the array initialization is done on a separate line, and not as a function call parameter. 

This works, too:
```
function main() {
    let n : i64 = 1
    let d = [1.0f64; n]
    let c = f(a: d)
}
```
Will update the post with this one, too

**Comment by onsah** [comment]
@mnlrsn 
I think I have found the issue. It is on https://github.com/SerenityOS/jakt/blob/b0be0a977d86b3e1f43e8b7d1b8aff1fdea51650/src/typechecker.rs#L4705 
This line checks the type of the size expression with the one given in the type hint. Which is incorrect. Because function call knows the types for the arguments it has type hint during the check.

I am preparing PR for the fix.
