### ISSUE TITLE
Running cat program fails with `call to 'fclose' is ambiguous`

### ISSUE THREAD

**Issue by sigmaSd** [SerenityOS/jakt#587]
Running cat program fails with 
`call to 'fclose' is ambiguous`

The problem is that
- in codgen an extern deceleration is added for fclose
- runtime also exports all stdio functions including fclose

Nb: fclose is not the only extern function affected

**Comment by sigmaSd** [comment]
I guess its on purpose, there is also cat-std

**Comment by lanmonster** [comment]
unable to reproduce on mac as of 1ea81c6. can users of other OSes comment on their experience?
