### ISSUE TITLE
jakttest/run-once.sh: no bash-isms present

### ISSUE THREAD

**Issue by paulwratt** [SerenityOS/jakt#884]
Can someone confirm that there are now no bash-isms in [jakttest/run-once.sh](https://github.com/SerenityOS/jakt/tree/main/jakttest/run-once.sh) with the latest removal of `pushd` & `popd`

If so then the shebang can be changed back to `#!/bin/sh` or `#!//usr/bin/env sh`.

**Comment by robryanx** [comment]
This can be closed now as it was changed to use a python script.
