### ISSUE TITLE
parser: A comma/EOL is not required between function parameters or arguments

### ISSUE THREAD

**Issue by mattco98** [SerenityOS/jakt#966]
See [this line](https://github.com/SerenityOS/jakt/blob/main/selfhost/typechecker.jakt#L4508) in `selfhost/typechecker.jakt`, which presumably has been compiling just fine for everyone up until this point.

This also compiles just fine:
```
function foo(a: i32 b: i32) {}
```

**Comment by sppmacd** [comment]
Looks related to #489.

**Comment by mattco98** [comment]
> Looks related to https://github.com/SerenityOS/jakt/issues/489.

Well this does cover a different error. That issue is a primarily a lexing error, as numeric literals should not be tokenized if they have a letter after them. This is a parsing error, specifically in the function definition/call parsing code.

**Comment by alimpfard** [comment]
Commas are optional in most parts of the language, but I think we originally came to an agreement that we should require either commas or newlines, turning the OP code into either:
```
function foo(a: i32, b: i32) {}
```
or:
```
function foo(
    a: i32
    b: i32
) {}
```

**Comment by mattco98** [comment]
> Commas are optional in most parts of the language, but I think we originally came to an agreement that we should require either commas or newline

Yeah, that's why I changed the title to include both comma and newlines. Currently, neither is required. Commas are simply discarded as whitespace if they happen to be there, and I think EOLs produce an error (not home to confirm that rn)

**Comment by feniljain** [comment]
Hey, @jntrnr seems to be saying, this should be a formatter level thing, rather than parser's problem, and we should be more open to this syntax as mentioned here:

https://github.com/SerenityOS/jakt/pull/988#issuecomment-1198796846

https://github.com/SerenityOS/jakt/pull/988#issuecomment-1199936147

So for now I closed the PR

**Comment by mattco98** [comment]
Huh, that's... interesting. But yes it seems this issue is no longer applicable, thanks for letting me know.
